# Change these first
owner: dev-ops-de # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://de.wikipedia.org
  - name: status.minusserver.com
    url: https://status.minusserver.com 

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.minusserver.com
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Uptime monitor and status page."
  introMessage: Alerting Page
  i18n:
  footer: This page is open source, powered by www.dev-ops.de
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/dev-ops-de/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
